### PR TITLE
Fix #251: increments hostIndex (host adress) on fallback

### LINKED ISSUE #251: DNS fallback resolution not working correctly
Following the recent NSOne DNS attack, we had a few customers reaching to use because their search wasn't working. For most of them it was because they were using an old API client version without the DNS fallback mechanism.

But for a few of them, that were using the very latest (3.14) version, they still had issues where some requests were targetting `algolia.net` and others `algolianet.com`. One user confirmed that reverting to 3.13 fixed the issue, the other monkey patched the code to force the `algolianet.com` endpoint.

I haven't been able to reproduce it on my side (DNS correctly working for me), but we did change this code in between those two releases, so we might have introduced a bug. I will dive more deeply into it as soon as I can but I'm taking a 11h flight tomorrow morning so not sure I'll be able to really focus on it.

All help is thus welcome into finding the bug and fix it as fast as we can.

### PR DESCRIPTION
**Pull request by bobylito**
NB: See #254 for previous discussions

This issue was caused because we do not distinguish CORS errors from DNS
resolution one and the code for incrementing the host index was moved into
the part that switches to the fallback.

Truth is that the current solution is not optimal as we are switching to
JSONP when we can't resolve the server name.

### CODE REVIEW

**Comment by vvo** [comment]
Cleaned dist/ and removed keys, updated commit message with:

```
When we are switching to fallback, increment host index so that JSONP
will use another host.

This issue was caused because we cannot distinguish CORS errors from DNS
resolution errors in the browser.

And the code for incrementing the host index was moved into the part
that switches to the fallback in
4ec5e6a.

Truth is that the current solution is not optimal as, in the browser,
we are switching to JSONP when we can't resolve the server name.

This is only done because we are not sure how CORS request can be
blocked (synchronously, asynchronously).

In a next version we would drop it and wait for real issues to show up.
74f1d54  
```

File: src/AlgoliaSearchCore.js [hunk 1]
```diff
@@ -360,19 +360,20 @@ AlgoliaSearchCore.prototype._jsonRequest = function(initialOpts) {
...
       }
 
+      client.hostIndex[initialOpts.hostType] = (client.hostIndex[initialOpts.hostType] + 1) % client.hosts[initialOpts.hostType].length;
+
       return doRequest(requester, reqOpts);
     }
 
     function retryRequest() {
-      client.hostIndex[initialOpts.hostType] = ++client.hostIndex[initialOpts.hostType] % client.hosts[initialOpts.hostType].length;
+      client.hostIndex[initialOpts.hostType] = (client.hostIndex[initialOpts.hostType] + 1) % client.hosts[initialOpts.hostType].length;
```
Comment (redox) [inline src/AlgoliaSearchCore.js]: From what I understand, not incrementing that `hostIndex` here will result in a loop always using the same host in case of `RequestTimeout` or `NodeNetwork`; is that correct?

Comment (bobylito) [inline src/AlgoliaSearchCore.js]: Yes, you are right @redox

Comment (redox) [inline src/AlgoliaSearchCore.js]: So that's a issue, right? In case of timeout/error/whatever: we always want to retry on the next host.

Comment (redox) [inline src/AlgoliaSearchCore.js]: Oh my bad, didn't get the assignment `client.hostIndex[initialOpts.hostType] =` -> we **ARE** incrmenting the `hostIndex` 👍
